[package]
name = "hobbs04067/mechaniccontroller"
version = "0.9.0"
license = "MIT"
authors = ["Hobbs0406"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = [
    "Source",
    "Source/*",
    "default.project.json",
    "wally.lock",
    "wally.toml",
]

[dependencies]